services:
  # Django Backend
  - type: web
    name: roblox-experience-finder-backend
    env: python
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn RobloxExperienceFinder.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: roblox-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"

  # React Frontend
  - type: web
    name: roblox-experience-finder-frontend
    env: node
    region: oregon
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: |
      cd frontend
      npx serve -s build -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18

  # Cron Jobs
  - type: cron
    name: daily-experiences
    env: python
    region: oregon
    schedule: "0 0 * * *" # Daily at midnight UTC
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py daily_exps
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: roblox-db
          property: connectionString

  - type: cron
    name: weekly-cleanup
    env: python
    region: oregon
    schedule: "0 0 * * 0" # Weekly on Sunday at midnight UTC
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py weekly_refresh_requests
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: roblox-db
          property: connectionString

  - type: cron
    name: weekly-experiences
    env: python
    region: oregon
    schedule: "0 0 * * 0" # Weekly on Sunday at midnight UTC
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py weekly_exps
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: roblox-db
          property: connectionString

# Database
databases:
  - name: roblox-db
    databaseName: roblox_experience_finder
    user: roblox_user
    region: oregon
