# Generated by Django 5.1.6 on 2025-05-20 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rootPlaceId', models.BigIntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('creator', models.CharField(default='Unknown', max_length=20)),
                ('description', models.TextField(null=True)),
                ('genre', models.CharField(default='All', max_length=255)),
                ('genre_l1', models.CharField(max_length=255, null=True)),
                ('genre_l2', models.CharField(max_length=255, null=True)),
                ('maxPlayers', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('icon', models.URLField()),
            ],
        ),
    ]
