# Generated by Django 5.1.6 on 2025-06-21 08:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='All', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rootPlaceId', models.BigIntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('creator', models.CharField(default='Unknown', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('genre', models.CharField(default='All', max_length=255)),
                ('genre_l1', models.CharField(blank=True, max_length=255, null=True)),
                ('genre_l2', models.CharField(blank=True, max_length=255, null=True)),
                ('maxPlayers', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('icon', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_url', models.URLField(default='', unique=True)),
                ('username', models.CharField(blank=True, default='Anonymous', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.experience')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='All', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.experience')),
            ],
        ),
    ]
