# Generated by Django 5.1.6 on 2025-07-06 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_admin_password_alter_admin_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
