# Generated by Django 5.2.4 on 2025-07-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_experience_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyExperience',
        ),
    ]
