# Generated by Django 5.2.4 on 2025-07-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_weeklyexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencerequest',
            name='experience_url',
            field=models.URLField(default=''),
        ),
    ]
