# Generated by Django 5.2.4 on 2025-07-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_experiencerequest_experience_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencerequest',
            name='experience_url',
            field=models.URLField(default='', unique=True),
        ),
    ]
