# Generated by Django 5.2.4 on 2025-07-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_experiencerequest_experience_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_accepted_requests', models.IntegerField(default=0)),
            ],
        ),
    ]
