# Generated by Django 5.2.4 on 2026-10-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='creator',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
