name: Update Experiences

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  update_experiences:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update experiences
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: "False"
        run: python manage.py exps_update_frequency
